<?php

/* global todo list
 *
 * support for all kinds of fields to 'autocomplete'
 * @todo: support for checkboxes
 * @todo: support for comboboxes
 * @todo: support for ...
 */

function multicomplete_menu() {
  $items = array();

  $items['multicomplete/js/%/f/%'] = array(
    'title' => '',
    'page callback' => 'multicomplete_autocomplete',
    'page arguments' => array(2, 4),
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );

  return $items;
}

function multicomplete_theme() {
  $items = array(
    'multicomplete_definition' => array(
      'render element' => 'element',
    ),
    'multicomplete_default_element' => array(
      'render element' => 'element',
    ),
    'multicomplete_render_multicomplete_value' => array(
      'render element' => 'element',
    ),
  );
  return $items;
}

function multicomplete_library() {
  $libraries = array();
  $libraries['multicomplete'] = array(
    'title' => 'Drupal auto-/multicomplete addon',
    'version' => '0.1',
    'js' => array(
      drupal_get_path('module', 'multicomplete') . '/multicomplete.js' => array('group' => JS_DEFAULT),
    ),
    'dependencies' => array(
      array('system', 'drupal.autocomplete'),
    ),
  );
  return $libraries;
}

function multicomplete_init() {
  drupal_add_library('multicomplete', 'multicomplete', TRUE);
  //drupal_add_js($path . '/multicomplete.js', array('weight' => -100));
}


/**
 * The default data retrieve callback will use the the multicomplete identifier as the function to call to retrieve
 * objects.
 *
 * @param $string
 *
 * @param $definition
 *
 * @return
 *
 * @todo: Document the default data type
 */
function multicomplete_type_default_data($string, &$definition) {
  $identifier = $definition['#identifier'];
  return call_user_func_array($identifier, array($string, &$definition));
}

/**
 *
 * @param $string
 *
 * @param $identifier
 *
 * @param $key_field
 *
 * @return
 *
 * @todo Document the multicomplete autocomplete function with all hooks etc etc.
 * @todo Document different hooks we provide / call
 * @todo Document $definition options
 */
function multicomplete_autocomplete($identifier, $key_field, $string) {
  $definition = array(); // initialize definition and defaults.
  $definition['#string'] = $string;
  $definition['#identifier'] = $identifier;
  $definition['#key'] = $key_field;
  $definition['#type'] = 'default';
  $definition['#fields'] = array($key_field);
  $definition['#strict'] = FALSE;

  $info_callback = $identifier . '_info';
  $info_field_callback = $identifier . '_' . $key_field . '_info';

  //Allow info callbacks to alter the $definition and also record executed callbacks in $definition itself.
  if (function_exists($info_callback)) {
    call_user_func_array($info_callback, array($key_field, $identifier, &$definition));
    $definition['#info_callbacks'][] = $info_callback;
  } //@todo: Why are we using this? Document all possible hooks PLEASE
  if (function_exists($info_field_callback)) {
    call_user_func_array($info_field_callback, array($key_field, $identifier, &$definition));
    $definition['#info_callbacks'][] = $info_field_callback;
  }

  //<editor-fold defaultstate="collapsed" desc=" Data retrieval stuff ">
  //Check what callback will be used to retrieve the data.
  $data_callback = 'multicomplete_type_' . $definition['#type'] . '_data';

  if (!function_exists($data_callback)) {
    $err_elements = array(
      'message' => array('#type' => 'markup', '#markup' => 'Given multicomplete type is not known to the system.'),
      'funcs' => array('#type' => 'markup', '#markup' => sprintf('<p>Function %s does not exist. </p>', $data_callback)),
    );
    watchdog('error', drupal_render($err_elements));
    return drupal_json_output(array());
  }

  $data = call_user_func_array($data_callback, array($string, &$definition));
  if (!is_array($data)) {
    $err_elements = array(
      'message' => array('#type' => 'markup', '#markup' => 'Multicomplete default data callback did not return a proper value.'),
      'funcs' => array('#type' => 'markup', '#markup' => sprintf('<p>Function call: %s("%s", "%s") </p>', $identifier, $string, $definition)),
      'return' => array('#type' => 'markup', '#markup' => sprintf('Return value: <br/><pre>%s</pre>', (isset($data) ? (string) $data : ''))),
    );
    watchdog('error', drupal_render($err_elements));
    return drupal_json_output(array());
  }

  //@todo: implement allowing other modules to alter the object list.
  //</editor-fold>
  // Cleanup mappings.
  _multicomplete_process_fields($definition);

  $pre_render = multicomplete_prepare_render($data, $definition);
  //@todo: Allow other modules to adjust the prepared render array.

  $render = _multicomplete_render($pre_render, $definition);

  return drupal_json_output($render);
}

// Preprocess fields and create the map (object field to form field)
function _multicomplete_process_fields(&$definition) {
  $maps = array();

  foreach ($definition['#fields'] as $data_field => &$form_field) {

    $field_name = is_array($form_field) ? array_shift($form_field) : $form_field;
    $key_name = is_int($data_field) ? $field_name : $data_field;

    $maps[$key_name] = $field_name;
    $definition['#fields'][$key_name] = is_array($form_field) ? $form_field : array();
    if (is_int($data_field)) {
      unset($definition['#fields'][$data_field]);
    }
  }
  $definition['#map'] = $maps;
}

/**
 *
 * @param $data
 *
 * @param $definition
 *
 * @param $key_field
 *
 * @return
 *
 * @todo: Document prepare render function.
 */
function multicomplete_prepare_render(&$data, &$definition) {
  $maps = $definition['#map'];
  $render_arr = array();
  foreach ($data as $obj) {
    $value = (array) $obj;
    $key_value = $value[$definition['#key']];

    $fields = array();
    $fields['#theme'] = array('multicomplete_definition');
    $fields['#definition'] = $definition;
    $fields['values'] = array();

    foreach (array_keys($value) as $obj_field) {

      $field = (isset($definition['#fields'][$obj_field]) && !$definition['#strict']) ? $definition['#fields'][$obj_field] : array();
      if (!isset($field['#type'])) {
        $field['#type'] = 'text';
      }

      if (array_key_exists($obj_field, $maps)) {
        $form_field = $maps[$obj_field];
      }
      elseif (!$definition['#strict']) {
        $form_field = $obj_field;
      }
      else {
        continue;
      }

      $field['#value'] = check_plain((string) $value[$obj_field]);

      if (is_bool($value[$obj_field])) {
        $field['#value'] = $value[$obj_field] ? '1' : '0';
        $field['#type'] = 'boolean';
      }

      $fields['values'][$form_field] = $field;
    }

    $format_callback = isset($definition['#element_format']) ? $definition['#element_format'] : 'multicomplete_render_element_format';
    if (!function_exists($format_callback)) {
      $err_elements = array(
        'message' => array('#type' => 'markup', '#markup' => 'Given multicomplete element formatter is not known to the system.'),
        'funcs' => array('#type' => 'markup', '#markup' => sprintf('<p>Function %s does not exist. </p>', $format_callback)),
      );
      watchdog('error', drupal_render($err_elements));
      return array();
    }
    $fields['format'] = call_user_func_array($format_callback, array(&$obj, &$fields['values'], &$definition));

    //@todo implement running the #element_format definition to prepare the format array.
    //@todo: Allow altering / hooking into this.

    $render_arr[$key_value] = $fields;
  }

  return $render_arr;
  //return array('definition' => $definition, 'render_arr' => $render_arr);
}

function _multicomplete_render($render, &$definition) {
  $rendered = array();
  foreach (array_keys($render) as $key) {
    $rendered[$key] = drupal_render($render[$key]);
  }
  return $rendered;
}

/**
 *
 * @param $variables
 *
 * @return
 *
 * @todo: Document de default multicomplete_definition theme.
 */
function theme_multicomplete_definition($variables) {
  //@todo implement proper rendering.
  $element = $variables['element'];
  $values = $element['values'];
  $format = $element['format'];
  $definition = $element['#definition'];
  $output = '';
  //$attributes = $variables['attributes'];

  $output .= '<div class="multicomplete-result">';
  $output .= '<span style="display: none" class="multicomplete-element">' . _multicomplete_render_fields($values, $definition) . '</span>';
  $output .= drupal_render($format);
  $output .= '</div>';
  return $output;
}

// Here we render the important field definitions to (ab)use in javascript land.
function _multicomplete_render_fields($values, $definition) {
  $output = '';
  foreach ($values as $key => $val) {
    $output .= '<span';
    $attributes = array(
      'data-field' => $key,
      'data-type' => $val['#type']
    );
    if ($definition['#key'] == $key) {
      $attributes['data-key'] = 1;
    }

    $output .= drupal_attributes($attributes);
    $output .= '>';
    $output .= $val['#value'];
    $output .= '</span>';
  }
  return $output;
}

/**
 *
 * @param $obj
 *
 * @param $values
 *
 * @param $definition
 *
 * @return
 *
 * @todo: document default render_element_format function
 */
function multicomplete_render_element_format(&$obj, &$values, &$definition) {
  return array(
    '#theme' => 'multicomplete_default_element',
    'object' => $obj,
    'definition' => $definition,
    'values' => $values,
  );
}

/**
 *
 * @param $variables
 *
 * @return
 *
 * @todo: document default multicomplete element render function. used by the render_element_format.
 */
function theme_multicomplete_default_element($variables) {
  $element = $variables['element'];
  $object = $element['object'];
  $definition = $element['definition'];
  $values = $element['values'];
  $output = '';
  $value_arr = array();

  foreach ($values as $val) {

    if (!isset($val['#hidden']) || $val['#hidden'] == FALSE) {

      switch ($val['#type']) {
        case 'text':
          $value_arr[] = $val['#value'];
          break;
        case 'boolean':
          break;
        default:
          $value_arr[] = (string) $val['#value'];
      }
    }
  }

  $output .= implode(', ', $value_arr);

  return $output;
}